# Error codes for consistent error messages across DataSanity
NONFINITE = "Non-finite values"
INVALID_DTYPE = "Non-numeric prices"
MISSING_COLS = "Missing required columns"
INDEX_NON_MONOTONIC = "Index is not monotonic"
DUPLICATE_TSTAMPS = "Duplicate timestamps not allowed"
TZ_NAIVE = "Naive timezone not allowed"
TZ_NON_UTC = "Non-UTC timezone not allowed"
NO_VALID_DT_INDEX = "No valid datetime index found"
PRICES_GT = "Prices >"
NEGATIVE_PRICES = "Negative prices"
OHLC_INVARIANT = "OHLC invariant violation"
LOOKAHEAD = "Lookahead contamination"
FUTURE_DATA = "Future data present"
